name: circleup
description: "A social networking app that helps users connect based on shared college or company backgrounds."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^12.1.3
  
  # UI & Animations
  flutter_animate: ^4.5.0
  flutter_card_swiper: ^6.1.0
  lottie: ^2.7.0
  
  # Utilities
  intl: ^0.18.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Dev Dependencies
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700 